---
# tasks file for remove_compass

# This installs, then removes, psexec in order to execute properly

- name: copies Compass uninstaller to C:\
  win_copy:
    src: CompassUninstall.exe
    dest: C:\Temp\ansbl_copy\

- name: install psexec
  win_chocolatey:
    name: psexec
    state: present
    ignore_checksums: true

- name: Runs .exe uninstaller via psexec
  win_command: '.\PsExec.exe -accepteula -i 1 -s C:\Temp\ansbl_copy\CompassUninstall.exe'
  args:
    chdir: C:\ProgramData\chocolatey\bin\

- name: remove psexec
  win_chocolatey:
    name: psexec
    state: absent