---
# tasks file for confirm_date

- name: "Ensure SAS license is up to date"
  lineinfile:
    name: '"C:\Program Files\SASHome\SASFoundation\9.4\setinit.log"'
    line: "Expiration:   30NOV2020."
    state: present
  check_mode: yes
  register: conf
  failed_when: (conf is changed) or (conf is failed)