---
# tasks file for sas_update

- name: "Ensure SAS license is up to date"
  win_lineinfile:
    path: C:\Program Files\SASHome\SASFoundation\9.4\setinit.log
    line: "Expiration:   30NOV2020."
    state: present
  check_mode: yes
  register: conf
  failed_when: (conf is failed)
  ignore_errors: true

- block:

  - name: Copy folder to C:\Temp (results in C:\Temp\ansbl_copy)
    win_copy:
      src: SAS94_9C8R3R_70138817_Win_X64_Wrkstn.txt
      dest: C:\Temp\ansbl_copy\
    register: create_license

  - name: Does SAS exist
    win_stat:
      path: '"C:\Program Files\SASHome\SASRenewalUtility\9.4\SASRenew.exe"'
    register: SAS_Installed

  - name: Update Sas License
    win_command: '"C:\Program Files\SASHome\SASRenewalUtility\9.4\SASRenew.exe" -s "datafile:c:\temp\ansbl_copy\SAS94_9C8R3R_70138817_Win_X64_Wrkstn.txt"'
    when: create_license.changed and SAS_Installed.stat.exists

  - name: Missing SAS
    debug:
      msg: SASRenew.exe Not Found
    when: SAS_Installed.stat.exists == False

  when: conf.changed

- name: Remove files
  win_file:
    path: C:\Temp\ansbl_copy
    state: absent

- block: 

  - name: Copy folder to C:\Temp (results in C:\Temp)
    win_copy:
      src: SAS94_9C8R3R_70138817_Win_X64_Wrkstn.txt
      dest: C:\Temp\
    # register: create_license2

  - name: Copy response to C:\Temp
    win_copy:
      src: sdwresponse.properties
      dest: C:\Temp\
    register: create_response

  - name: Update License (with Deployment Manager)
    win_shell: '& "C:\Program Files\SASHome\SASDeploymentManager\9.4\sasdm.exe" -quiet -responsefile "C:\temp\sdwresponse.properties"'
    when: create_response.changed
    register: results
    # changed_when: results.rc == 4294967295

 # - name: wait for update
 #   wait_for:
 #     path: C:\Program Files\SASHome\SASFoundation\9.4\setinit.log
 #     search_regex: "Expiration:   30NOV2020."

  - name: Remove files
    win_file:
      path: 'C:\Temp\SAS94_9C8R3R_70138817_Win_X64_Wrkstn.txt'
      state: absent

  - name: Remove property file
    win_file:
      path: 'C:\temp\sdwresponse.properties'
      state: absent
  
  when: conf is failed