---
# tasks file for veyon_Master

- name: Install veyon
  win_chocolatey:
    name: veyon
    state: present
    package_params: '"/Master"'

- name: update veyon
  win_chocolatey:
    name: veyon
    state: latest
    package_params: '"/Master"'
    force: yes

- name: configure destination
  win_command: .\veyon-cli config set FileTransfer/DestinationDirectory C:\Temp\
  args:
    chdir: C:\Progra~1\Veyon

- name: remote connection notification
  win_command: .\veyon-cli.exe config set Service/RemoteConnectionNotifications true
  args:
    chdir: C:\Progra~1\Veyon