---
# tasks file for install_Snagit

- name: Copy folder to C:\Temp (results in C:\Temp\ansbl_copy)
  win_copy:
    src: Snagit/
    dest: C:\Temp\ansbl_copy\

- name: runs Snagit installer
  win_shell: msiexec /i "C:\temp\ansbl_copy\snagit.msi" /qn TRANSFORMS="C:\temp\ansbl_copy\snagit-fix.mst"