---
# tasks file for veyon_loadConfig; this is for the Podium computer
#Note: There are multiple lab masters to be chosen from, ensure that the correct one is transferred!


- debug:
    msg: Importing "labmaster-SHB{{ lab }}.json"

- name: Copy config to C:\Temp (results in C:\Temp\ansbl_copy)
  win_copy:
    src: "labmaster-SHB{{ lab }}.json"
    dest: C:\Temp\ansbl_copy\

- name: load config file for veyon lab master
  win_command: .\veyon-cli.exe config import "C:\Temp\ansbl_copy\labmaster-SHB{{ lab }}.json"
  args:
    chdir: C:\Progra~1\Veyon

- name: restart Veyon service
  win_command: .\veyon-cli.exe service restart
  args:
    chdir: C:\Progra~1\Veyon