---
# tasks file for install_compass

- name: Copy folder to C:\Temp\ansbl_copy
  win_copy:
    src: Compass_Setup.exe
    dest: C:\Temp\ansbl_copy\

- name: runs Compass installer
  win_command: '.\Compass_Setup.exe /Silent Path="C:\Certiport\Compass" /UpdateSchedule Weekly /UpdateTime 00:30'
  args:
    chdir: C:\temp\ansbl_copy\

- name: Copy .enc to appropriate Compass folder
  win_copy:
    src: CTCConfig.enc
    dest: c:\Certiport\Compass\Data\CTCConfig.enc