- hosts: test
  roles:
        - run_Dell_CMD_Updt
        #- copy_Cybertrack
        #- copy_data
        #- copy_Camtasia
        #- copy_Snagit
        #- copy_EIT_Shortcut
        #- copy_compass
        #- copy_Logitech
        #- copy_enc
        #- install_Cybertrack
        #- install_Camtasia
        #- uninstall_Snagit
        #- install_Snagit
        #- install_veyon
        #- install_compass
        #- copy_data
        #- install_SAP
        #- run_haspdinst.exe
        #- query_Compass
        #- repair_O365
        #- remove_Mendix
        #- copy_install_VMware16