- hosts: SHB-3-56
  roles:
        #- copy_Cybertrack
        #- copy_data
        #- copy_Camtasia
        #- copy_Snagit
        #- copy_EIT_Shortcut
        #- copy_compass
        #- install_Cybertrack
        #- install_Camtasia
        - install_Snagit
        #- install_veyon
        #- install_compass
        #- install_SAP
        #- cleanup_ansbl_copy