---
# tasks file for get_software

#- name: Queries for Office
 # win_shell: Get-CimInstance win32_product -Filter "Name like '%Office%'" | Select-Object -first 1 | Format-wide -Property Version | Out-String
  #register: Office_out

#- name: Queries for SPSS
 # win_shell: Get-CimInstance win32_product -Filter "Name like '%SPSS%'" | Format-wide -Property Version | Out-String
  #register: SPSS_out

#- name: Queries for Stata
 # win_shell: Get-CimInstance win32_product -Filter "Name like '%Stata'" | Format-wide -Property Version | Out-String
  #register: Stata_out

#- name: Queries for Matlab
 # win_shell: Get-CimInstance win32_product -Filter "Name like '%matlab%'" | Format-wide -Property Version | Out-String
  #register: Matlab_out

#- name: Queries for SAP
 # win_shell: Get-CimInstance win32_product -Filter "Name like '%SAP%'" | Format-wide -Property Version | Out-String
  #register: SAP_out

#- name: Queries for Veyon
 # win_shell: Get-CimInstance win32_product -Filter "Name like '%Veyon%'" | Format-wide -Property Version | Out-String
  #register: Veyon_out

 - name: Queries for Zoom
   win_shell: Get-CimInstance win32_product -Filter "Name like '%Zoom%'" | Format-wide -Property Version | Out-String
   register: Zoom_out

#- name: Queries for Skype
 # win_shell: Get-CimInstance win32_product -Filter "Name like '%Skype%'" | Format-wide -Property Version | Out-String
  #register: Skype_out

#- name: Queries for Creative Cloud
 # win_shell: Get-CimInstance win32_product -Filter "Name like '%Creative%Cloud%'" | Format-wide -Property Version | Out-String
  #register: CreativeCloud_out  

#- name: output
 # shell: echo "{% if True -%}{{ ansible_hostname }},{{ Office_out.stdout | replace('^M', '') }},{{ SPSS_out.stdout | replace('^M', '') }},{{ Stata_out.stdout | replace('^M', '') }},{{ Matlab_out.stdout | replace('^M', '') }},{{ SAP_out.stdout | replace('^M', '') }},{{ Veyon_out.stdout | replace('^M', '') }},{{ Zoom_out.stdout | replace('^M', '') }},{{ Skype_out.stdout | replace('^M', '') }},{{ CreativeCloud_out.stdout | replace('^M', '') }}\n{%- endif %} " >> /mnt/c/temp/SoftwareList.csv
  #args:
   # executable: /bin/bash
  #delegate_to: localhost  