---
# tasks file for get_MAC

- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts[item]['macaddress']

- name: get_MAC
  ansible.builtin.debug:  
    msg: "Node {{ inventory_hostname }} has MAC {{ansible_facts.ansible_interfaces}}"

#- name: Gathering MAC address
#  win_shell: Get-CimInstance win32_networkadapterconfiguration | select Description, #MACAddress | where {$_.MACAddress -ne $null } | where {$_.Description -match "Intel" }
#  register: result

#- name: print results
#  debug:
#    msg: "{{result.stdout}}"