---
# tasks file for get_MAC

- name: get_MAC
  win_shell: get-NetAdapter -name "Ethernet*" | Select-Object -ExpandProperty macaddress
  register: resultMAC

- name: get_OS
  win_shell: (get-ciminstance -class win32_operatingsystem).caption
  register: resultOS

- name: get_release
  win_shell: (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").ReleaseId
  register: resultVER

- name: print host information
  ansible.builtin.debug:  
    msg: "{{ inventory_hostname }}, {{resultMAC.stdout | regex_replace('\r', '') | trim }}, {{ resultOS.stdout | regex_replace('\r\n', '') | trim }}, {{ resultVER.stdout | regex_replace('\r\n', '') | trim }}."